name: Deploy Applications
on:
  push:
    branches: [master, test-build]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: antowa-qq
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  ACTOR: ${{ github.actor }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Setup environment variables for production
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "SERVER_IP=206.81.18.138" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build API Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todo-trpc-fastify:${{ github.sha }} .
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todo-trpc-fastify:${{ github.sha }}

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASS_PHRASE }}
          envs: GITHUB_TOKEN,ACTOR,GITHUB_SHA,IMAGE_NAME,REGISTRY
          script: |
            docker login -u $ACTOR -p $GITHUB_TOKEN ghcr.io
            docker pull $REGISTRY/$IMAGE_NAME/todo-trpc-fastify:$GITHUB_SHA
            docker stop todo-trpc-fastify || true && docker rm todo-trpc-fastify || true
            docker run -d --restart always --name todo-trpc-fastify -p 3001:3001 -e NODE_ENV=production $REGISTRY/$IMAGE_NAME/todo-trpc-fastify:$GITHUB_SHA
            docker image prune -af